---
Name: app
After: 'framework/*','cms/*'
---
LeftAndMain:
  extra_requirements_css:
    - themes/otp/css/editor.css
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SiteConfig:
    extensions:
      - OTPConfigs
    Icons:
      icon-head-arrow : 'Arrow'
      icon-arrow-down : 'Arrow Down'
      icon-external-link : 'External Link'
      icon-apostrophe : 'Apostrophe'
      icon-twitter: 'Twitter'
      icon-facebook: 'Facebook'
      icon-link: 'Link'
      icon-dot: 'Dot'
      icon-tick: 'Tick'
      icon-mail: 'Mail'
      icon-phone: 'Phone'
      icon-play: 'Play Button'
      icon-info: 'Info List'
      icon-cta: 'File List'
      icon-download: 'Download'
      icon-search: 'Search'
Director:
  rules:
    'tile//$Action/$ID': 'FilterableTile_Counter'
SSViewer:
  theme: 'otp'
Page:
  extensions:
    - ElementPageExtension
  allowed_elements:
    - WayFinder
    - HearFromOthers
    - ElementContent
    - Carousel
    - CTAElement
    - Accordion
    - SidebarTestimony
    - SidebarImageElement
    - ElementImage
    - ElementFile
    - ElementInternalLink
    - ElementExternalLink
    - MasonryContentsWithFilters
    - MasonryContent
    - LinksComponent
    - TabbedCheckList
    - CaseStudy
    - VideoComponent
    - CheckList
    - CarouselWithUpperLetter
    - MatrixElement
Controller:
  extensions:
    - ControllerExtension
FooterLinkBlock:
  extensions:
    - Linkable
FooterLink:
  extensions:
    - Linkable
WayFinderFilter:
  extensions:
    - Linkable
WayFinderItem:
  extensions:
    - Linkable
CTAElement:
  extensions:
    - Linkable
RelatedPage:
  extensions:
    - Linkable
RelatedPageBox:
  extensions:
    - Linkable
MasonryTile:
  extensions:
    - Linkable
MasonryTileLink:
  extensions:
    - Linkable
LinkElement:
  extensions:
    - Linkable
LinksComponent:
  extensions:
    - Linkable
FilterableMasonryTile:
  extensions:
    - FilterableTile
FilterableMasonryImageTile:
  extensions:
    - FilterableTile
FilterableSmallMasonryTile:
  extensions:
    - FilterableTile
ElementContent:
  extensions:
    - ElementContentExtension
BaseElement:
  extensions:
    - BaseElementExtension
GlossaryItem:
  extensions:
    - Contactable
CheckListBlockItem:
  extensions:
    - Contactable
MasonryContent:
  extensions:
    - Contactable
SiteTree:
  extensions:
    - Contactable
ElementFile:
  title: "CTA to Download File"
ElementExternalLink:
  title: "Featured external link"
ElementInternalLink:
  title: "Featured internal link"
ElementImage:
  title: "Inline image"
ElementExternalLink:
  defaults:
    NewWindow: 1