---
Name: app

---
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - themes/otp/css/editor.css
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - OP\Studentsuccess\OTPConfigs
  Icons:
    icon-head-arrow: Arrow
    icon-arrow-down: 'Arrow Down'
    icon-external-link: 'External Link'
    icon-apostrophe: Apostrophe
    icon-twitter: Twitter
    icon-facebook: Facebook
    icon-link: Link
    icon-dot: Dot
    icon-tick: Tick
    icon-mail: Mail
    icon-phone: Phone
    icon-play: 'Play Button'
    icon-info: 'Info List'
    icon-cta: 'File List'
    icon-download: Download
    icon-search: Search
SilverStripe\Control\Director:
  rules:
    tile//$Action/$ID: OP\Studentsuccess\FilterableTile_Counter
SilverStripe\View\SSViewer:
  themes:
    - otp
    - '$default'
DNADesign\Elemental\Extensions\ElementalPageExtension:
  ignored_classes:
    - OP\Studentsuccess\ActivityPage
    - OP\Studentsuccess\FilterableCheckList
Page:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
  allowed_elements:
    - DNADesign\Elemental\Models\ElementContent
    - OP\Studentsuccess\Carousel
    - OP\Studentsuccess\CTAElement
    - OP\Studentsuccess\ContactElement
    - OP\Studentsuccess\SidebarTestimony
    - OP\Studentsuccess\InteractiveList
    - OP\Studentsuccess\SingleLevelCheckList
    - OP\Studentsuccess\SingleLevelList
    - OP\Studentsuccess\SidebarImageElement
    - OP\Studentsuccess\SidebarHelp
    - OP\Studentsuccess\ElementImage
    - OP\Studentsuccess\ElementFile
    - OP\Studentsuccess\ElementLink
    - OP\Studentsuccess\ReferencesElement
    - OP\Studentsuccess\LinksComponent
    - OP\Studentsuccess\CaseStudy
    - OP\Studentsuccess\VideoComponent
    - OP\Studentsuccess\CheckList
    - OP\Studentsuccess\CarouselWithUpperLetter
    - OP\Studentsuccess\MatrixElement
OP\Studentsuccess\AccordionPage:
  allowed_elements:
    - OP\Studentsuccess\Accordion
OP\Studentsuccess\HomePage:
  allowed_elements:
    - OP\Studentsuccess\HearFromOthers
OP\Studentsuccess\LandingPage:
  allowed_elements:
    - OP\Studentsuccess\MasonryContent
OP\Studentsuccess\LandingSearchPage:
  allowed_elements:
    - OP\Studentsuccess\MasonryContentsWithFilters
SilverStripe\Control\Controller:
  extensions:
    - OP\Studentsuccess\ControllerExtension
OP\Studentsuccess\FooterLinkBlock:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\FooterLink:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\WayFinderFilter:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\WayFinderItem:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\CTAElement:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\RelatedPage:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\RelatedPageBox:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\MasonryTile:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\MasonryTileLink:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\LinkElement:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\LinksComponent:
  extensions:
    - OP\Studentsuccess\Linkable
OP\Studentsuccess\FilterableMasonryTile:
  extensions:
    - OP\Studentsuccess\FilterableTile
OP\Studentsuccess\FilterableMasonryImageTile:
  extensions:
    - OP\Studentsuccess\FilterableTile
OP\Studentsuccess\FilterableSmallMasonryTile:
  extensions:
    - OP\Studentsuccess\FilterableTile
DNADesign\Elemental\Models\ElementContent:
  extensions:
    - OP\Studentsuccess\ElementContentExtension

OP\Studentsuccess\GlossaryItem:
  extensions:
    - OP\Studentsuccess\Contactable
OP\Studentsuccess\CheckListBlockItem:
  extensions:
    - OP\Studentsuccess\Contactable
OP\Studentsuccess\MasonryContent:
  extensions:
    - OP\Studentsuccess\Contactable
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - OP\Studentsuccess\Contactable
OP\Studentsuccess\ElementFile:
  title: 'CTA to Download File'
  extensions:
    - OP\Studentsuccess\ElementFileExtension
ElementExternalLink:
  title: 'Featured external link'
  defaults:
    NewWindow: 1
ElementInternalLink:
  extensions:
    - OP\Studentsuccess\ElementInternalLinkExtension
  title: 'Featured internal link'

SilverStripe\MimeValidator\MimeUploadValidator:
  MimeTypes:
    dmg:
      - application/x-apple-diskimage
      - application/octet-stream


DNADesign\Elemental\Models\BaseElement:
  extensions:
    - OP\Studentsuccess\OPBaseElementExtension


SilverStripe\Core\Injector\Injector:
  DNADesign\ElementalList\Extension\BaseElementCMSEditLinkExtension:
    class: OP\Studentsuccess\OPBaseElementCMSEditLinkExtension
  DNADesign\Elemental\Models\ElementContent:
    class: OP\Studentsuccess\OPElementContentInjector
