---
Name: app
After: 'framework/*','cms/*'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - themes/otp/css/editor.css
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - OP\studentsuccess\OTPConfigs
  Icons:
    icon-head-arrow: Arrow
    icon-arrow-down: 'Arrow Down'
    icon-external-link: 'External Link'
    icon-apostrophe: Apostrophe
    icon-twitter: Twitter
    icon-facebook: Facebook
    icon-link: Link
    icon-dot: Dot
    icon-tick: Tick
    icon-mail: Mail
    icon-phone: Phone
    icon-play: 'Play Button'
    icon-info: 'Info List'
    icon-cta: 'File List'
    icon-download: Download
    icon-search: Search
SilverStripe\Control\Director:
  rules:
    tile//$Action/$ID: OP\studentsuccess\FilterableTile_Counter
SilverStripe\View\SSViewer:
  theme: otp
ElementPageExtension:
  ignored_classes:
    - OP\studentsuccess\ActivityPage
    - OP\studentsuccess\FilterableCheckList
Page:
  extensions:
    - ElementPageExtension
  allowed_elements:
    - DNADesign\Elemental\Models\ElementContent
    - OP\studentsuccess\Carousel
    - OP\studentsuccess\CTAElement
    - OP\studentsuccess\ContactElement
    - OP\studentsuccess\SidebarTestimony
    - OP\studentsuccess\InteractiveList
    - OP\studentsuccess\SingleLevelCheckList
    - OP\studentsuccess\SingleLevelList
    - OP\studentsuccess\SidebarImageElement
    - OP\studentsuccess\SidebarHelp
    - ElementImage
    - OP\studentsuccess\ElementTable
    - ElementFile
    - ElementLink
    - OP\studentsuccess\ReferencesElement
    - OP\studentsuccess\LinksComponent
    - OP\studentsuccess\CaseStudy
    - OP\studentsuccess\VideoComponent
    - OP\studentsuccess\CheckList
    - OP\studentsuccess\CarouselWithUpperLetter
    - OP\studentsuccess\MatrixElement
OP\studentsuccess\AccordionPage:
  allowed_elements:
    - OP\studentsuccess\Accordion
OP\studentsuccess\HomePage:
  allowed_elements:
    - OP\studentsuccess\HearFromOthers
OP\studentsuccess\LandingPage:
  allowed_elements:
    - OP\studentsuccess\MasonryContent
OP\studentsuccess\LandingSearchPage:
  allowed_elements:
    - OP\studentsuccess\MasonryContentsWithFilters
SilverStripe\Control\Controller:
  extensions:
    - OP\studentsuccess\ControllerExtension
OP\studentsuccess\FooterLinkBlock:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\FooterLink:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\WayFinderFilter:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\WayFinderItem:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\CTAElement:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\RelatedPage:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\RelatedPageBox:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\MasonryTile:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\MasonryTileLink:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\LinkElement:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\LinksComponent:
  extensions:
    - OP\studentsuccess\Linkable
OP\studentsuccess\FilterableMasonryTile:
  extensions:
    - OP\studentsuccess\FilterableTile
OP\studentsuccess\FilterableMasonryImageTile:
  extensions:
    - OP\studentsuccess\FilterableTile
OP\studentsuccess\FilterableSmallMasonryTile:
  extensions:
    - OP\studentsuccess\FilterableTile
DNADesign\Elemental\Models\ElementContent:
  extensions:
    - OP\studentsuccess\ElementContentExtension
DNADesign\Elemental\Models\BaseElement:
  extensions:
    - OP\studentsuccess\OPBaseElementExtension
OP\studentsuccess\GlossaryItem:
  extensions:
    - OP\studentsuccess\Contactable
OP\studentsuccess\CheckListBlockItem:
  extensions:
    - OP\studentsuccess\Contactable
OP\studentsuccess\MasonryContent:
  extensions:
    - OP\studentsuccess\Contactable
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - OP\studentsuccess\Contactable
ElementFile:
  title: 'CTA to Download File'
  extensions:
    - OP\studentsuccess\ElementFileExtension
ElementExternalLink:
  title: 'Featured external link'
  defaults:
    NewWindow: 1
ElementInternalLink:
  extensions:
    - OP\studentsuccess\ElementInternalLinkExtension
  title: 'Featured internal link'
ElementImage:
  title: 'Inline image'
SilverStripe\MimeValidator\MimeUploadValidator:
  MimeTypes:
    dmg:
      - application/x-apple-diskimage
      - application/octet-stream
SilverStripe\Core\Injector\Injector:
  DNADesign\Elemental\Models\ElementalArea:
    class: OP\studentsuccess\ElementalAreaExtension
