mappings:
  OPBaseElementExtension: OP\Studentsuccess\OPBaseElementExtension
  Contactable: OP\Studentsuccess\Contactable
  ControllerExtension: OP\Studentsuccess\ControllerExtension 
  ElementalAreaExtension: OP\Studentsuccess\ElementalAreaExtension
  ElementContentExtension: OP\Studentsuccess\ElementContentExtension
  ElementFileExtension: OP\Studentsuccess\ElementFileExtension
  ElementInternalLinkExtension: OP\Studentsuccess\ElementInternalLinkExtension
  OTPConfigs: OP\Studentsuccess\OTPConfigs
  Accordion: OP\Studentsuccess\Accordion
  Accordion_ElementPublishChildren: OP\Studentsuccess\Accordion_ElementPublishChildren
  AccordionItem: OP\Studentsuccess\AccordionItem
  Carousel: OP\Studentsuccess\Carousel
  CarouselSlide: OP\Studentsuccess\CarouselSlide
  CarouselSlideWithUpperLetter: OP\Studentsuccess\CarouselSlideWithUpperLetter
  CarouselTextSlide: OP\Studentsuccess\CarouselTextSlide
  CarouselTextSlide_NoTitle: OP\Studentsuccess\CarouselTextSlide_NoTitle
  CarouselTwoColumnSlide: OP\Studentsuccess\CarouselTwoColumnSlide
  CarouselWithUpperLetter: OP\Studentsuccess\CarouselWithUpperLetter
  CaseStudy: OP\Studentsuccess\CaseStudy
  CheckList: OP\Studentsuccess\CheckList
  CheckListCollection: OP\Studentsuccess\CheckListCollection
  CheckListItem: OP\Studentsuccess\CheckListItem
  InteractiveList: OP\Studentsuccess\InteractiveList
  ListCollectionItem: OP\Studentsuccess\ListCollectionItem
  SingleLevelCheckList: OP\Studentsuccess\SingleLevelCheckList
  SingleLevelList: OP\Studentsuccess\SingleLevelList
  ContactElement: OP\Studentsuccess\ContactElement
  CTAElement: OP\Studentsuccess\CTAElement
  ElementTable: OP\Studentsuccess\ElementTable
  HearFromOthers: OP\Studentsuccess\HearFromOthers
  VideoComponent: OP\Studentsuccess\VideoComponent
  LinksComponent: OP\Studentsuccess\LinksComponent
  FilterableMasonryImageTile: OP\Studentsuccess\FilterableMasonryImageTile
  FilterableMasonryTile: OP\Studentsuccess\FilterableMasonryTile
  FilterableSmallMasonryImageTile: OP\Studentsuccess\FilterableSmallMasonryImageTile
  FilterableSmallMasonryTile: OP\Studentsuccess\FilterableSmallMasonryTile
  FilterableTile: OP\Studentsuccess\FilterableTile
  FilterableTile_Counter: OP\Studentsuccess\FilterableTile_Counter
  LinkListMasonryTile: OP\Studentsuccess\LinkListMasonryTile
  MasonryContent: OP\Studentsuccess\MasonryContent
  MasonryContentsWithFilters: OP\Studentsuccess\MasonryContentsWithFilters
  MasonryImageTile: OP\Studentsuccess\MasonryImageTile
  MasonryTile: OP\Studentsuccess\MasonryTile
  MasonryTileLink: OP\Studentsuccess\MasonryTileLink
  SmallMasonryTile: OP\Studentsuccess\SmallMasonryTile
  MatrixElement: OP\Studentsuccess\MatrixElement
  ReferencesElement: OP\Studentsuccess\ReferencesElement
  SidebarImageElement: OP\Studentsuccess\SidebarImageElement
  SidebarTestimony: OP\Studentsuccess\SidebarTestimony
  SidebarHelp: OP\Studentsuccess\SidebarHelp
  CheckListBlock: OP\Studentsuccess\CheckListBlock
  CheckListBlockItem: OP\Studentsuccess\CheckListBlockItem
  CheckListTab: OP\Studentsuccess\CheckListTab
  FilterableCheckListBlock: OP\Studentsuccess\FilterableCheckListBlock
  TabbedCheckList: OP\Studentsuccess\TabbedCheckList
  WayFinder: OP\Studentsuccess\WayFinder
  WayFinderFilter: OP\Studentsuccess\WayFinderFilter
  WayFinderImageItem: OP\Studentsuccess\WayFinderImageItem
  WayFinderItem: OP\Studentsuccess\WayFinderItem
  FooterLink: OP\Studentsuccess\FooterLink
  FooterLinkBlock: OP\Studentsuccess\FooterLinkBlock
  GlossaryItem: OP\Studentsuccess\GlossaryItem
  GlossaryType: OP\Studentsuccess\GlossaryType
  LinkElement: OP\Studentsuccess\LinkElement
  RelatedPage: OP\Studentsuccess\RelatedPage
  RelatedPageBox: OP\Studentsuccess\RelatedPageBox
  AccordionPage: OP\Studentsuccess\AccordionPage
  ActivityPage: OP\Studentsuccess\ActivityPage
  ActivityPage_Controller: OP\Studentsuccess\ActivityPage_Controller
  ActivityPage_Activity: OP\Studentsuccess\ActivityPage_Activity
  ActivityPage_Activity_Content: OP\Studentsuccess\ActivityPage_Activity_Content
  FilterableCheckList: OP\Studentsuccess\FilterableCheckList
  FilterableCheckList_Controller: OP\Studentsuccess\FilterableCheckList_Controller
  GlossaryPage: OP\Studentsuccess\GlossaryPage
  GlossaryPage_Controller: OP\Studentsuccess\GlossaryPage_Controller
  HomePage: OP\Studentsuccess\HomePage
  HomePage_Controller: OP\Studentsuccess\HomePage_Controller
  LandingPage: OP\Studentsuccess\LandingPage
  LandingSearchPage: OP\Studentsuccess\LandingSearchPage
  WasThisHelpfulReport: OP\Studentsuccess\WasThisHelpfulReport
  SearchPage: OP\Studentsuccess\SearchPage
  CoreConfigs: OP\Studentsuccess\CoreConfigs
  ImageExtension: OP\Studentsuccess\ImageExtension
  ImageExtensionHelper: OP\Studentsuccess\ImageExtensionHelper
  Linkable: OP\Studentsuccess\Linkable
  OPCwpControllerExtension: OP\Studentsuccess\OPCwpControllerExtension
  DateUtils: OP\Studentsuccess\DateUtils
  FormUtils: OP\Studentsuccess\FormUtils
  ShortCodeUtils: OP\Studentsuccess\ShortCodeUtils
  SS_MinifiedResponseExtension: OP\Studentsuccess\SS_MinifiedResponseExtension
  SS_MinifiedResponse: OP\Studentsuccess\SS_MinifiedResponse
  StringUtils: OP\Studentsuccess\StringUtils
  CreateJobsTask: OP\Studentsuccess\CreateJobsTask
  internalExternalLinkTask: OP\Studentsuccess\internalExternalLinkTask
