
<section class='case-study-holder'>
	<div class='case-study'>

		<div class='left'>
			<picture>
				<img src='./images/case-study.png'>
			</picture>
			<span class='icon icon-apostrophe'></span>
			<p>
				Lorem ipsum dolor 
				sit amet consect vil
				set. Cras vehicula 
				dolor sit amet 
				tincidunt ultrices.
			</p>
		</div>
		<div class='right'>
			<h3>A student story</h3>
			<p>
				A collection born out of frustration with the amount of waste generated by
				the fashion industry has garnered national recognition for designer, Fiona 
				Clements.
			</p>
			<p>
				Fusce id sollicitudin libero. Nulla pulvinar lorem sit amet justo cursus semper. Fusce quam urna, posuere varius convallis in, dapibus non lacus. Ut tempor tempor elit id commodo. Etiam ultricies arcu non dui hendrerit, non aliquam est volutpat. Integer in suscipit tellus. Morbi ornare ligula libero, faucibus pellentesque velit porta at. Vivamus eu volutpat lectus. Suspendisse at dolor vel eros placerat vulputate ut et risus. Proin euismod turpis et dictum lobortis. Phasellus at viverra dui. Mauris nec ornare enim. Pellentesque iaculis orci ipsum, non finibus felis egestas elementum.
			</p>

			<p>
				Donec mattis iaculis finibus. Nulla at leo sodales, sagittis tellus et, tempus mauris. In id risus nisi. Phasellus vitae pellentesque velit, vel varius tortor. Nulla suscipit ante et aliquet euismod. Suspendisse potenti. Sed in auctor metus, eget aliquet lacus. Ut sed posuere ex. Aliquam interdum tincidunt maximus. Praesent aliquet eleifend mi quis sagittis. Quisque venenatis at ipsum id lobortis. Sed ultrices commodo nulla, sit amet rutrum elit cursus at. Aenean nulla nisl, tincidunt eu ultricies et, semper a elit. In eleifend dictum sodales.
			</p>

			<p>
				Pellentesque bibendum tincidunt ligula, at sagittis elit tempus vitae. Sed nec luctus tellus. Nunc facilisis elementum risus, faucibus venenatis lorem iaculis vel. Cras a purus id odio semper aliquet. Aenean sit amet lorem quis sapien vulputate porttitor. Aliquam placerat lacus lacus, sit amet viverra odio facilisis eu. Cras tincidunt diam fermentum felis accumsan, at scelerisque arcu pulvinar. Nunc finibus vulputate pulvinar. In id urna at mauris imperdiet porta id ac metus. Vivamus quis lacus sed orci facilisis tempor. Proin eu justo urna.
			</p>

		</div>

		<div class='clear'>&nbsp;</div>
	</div>


	<div class='case-study red'>

		<div class='left'>
			<picture>
				<img src='./images/case-study.png'>
			</picture>
			<span class='icon icon-apostrophe'></span>
			<p>
				Lorem ipsum dolor 
				sit amet consect vil
				set. Cras vehicula 
				dolor sit amet 
				tincidunt ultrices.
			</p>
		</div>
		<div class='right'>
			<h3>A student story</h3>
			<p>
				A collection born out of frustration with the amount of waste generated by
				the fashion industry has garnered national recognition for designer, Fiona 
				Clements.
			</p>
			<p>
				Fusce id sollicitudin libero. Nulla pulvinar lorem sit amet justo cursus semper. Fusce quam urna, posuere varius convallis in, dapibus non lacus. Ut tempor tempor elit id commodo. Etiam ultricies arcu non dui hendrerit, non aliquam est volutpat. Integer in suscipit tellus. Morbi ornare ligula libero, faucibus pellentesque velit porta at. Vivamus eu volutpat lectus. Suspendisse at dolor vel eros placerat vulputate ut et risus. Proin euismod turpis et dictum lobortis. Phasellus at viverra dui. Mauris nec ornare enim. Pellentesque iaculis orci ipsum, non finibus felis egestas elementum.
			</p>

			<p>
				Donec mattis iaculis finibus. Nulla at leo sodales, sagittis tellus et, tempus mauris. In id risus nisi. Phasellus vitae pellentesque velit, vel varius tortor. Nulla suscipit ante et aliquet euismod. Suspendisse potenti. Sed in auctor metus, eget aliquet lacus. Ut sed posuere ex. Aliquam interdum tincidunt maximus. Praesent aliquet eleifend mi quis sagittis. Quisque venenatis at ipsum id lobortis. Sed ultrices commodo nulla, sit amet rutrum elit cursus at. Aenean nulla nisl, tincidunt eu ultricies et, semper a elit. In eleifend dictum sodales.
			</p>


		</div>

		<div class='clear'>&nbsp;</div>
	</div>


	<div class='case-study blue'>

		<div class='left'>
			<picture>
				<img src='./images/case-study.png'>
			</picture>
			<span class='icon icon-apostrophe'></span>
			<p>
				Lorem ipsum dolor 
				sit amet consect vil
				set. Cras vehicula 
				dolor sit amet 
				tincidunt ultrices.
			</p>
		</div>
		<div class='right'>
			<h3>A student story</h3>
			<p>
				A collection born out of frustration with the amount of waste generated by
				the fashion industry has garnered national recognition for designer, Fiona 
				Clements.
			</p>
			<p>
				Donec mattis iaculis finibus. Nulla at leo sodales, sagittis tellus et, tempus mauris. In id risus nisi. Phasellus vitae pellentesque velit, vel varius tortor. Nulla suscipit ante et aliquet euismod. Suspendisse potenti. Sed in auctor metus, eget aliquet lacus. Ut sed posuere ex. Aliquam interdum tincidunt maximus. Praesent aliquet eleifend mi quis sagittis. Quisque venenatis at ipsum id lobortis. Sed ultrices commodo nulla, sit amet rutrum elit cursus at. Aenean nulla nisl, tincidunt eu ultricies et, semper a elit. In eleifend dictum sodales.
			</p>

			<p>
				Pellentesque bibendum tincidunt ligula, at sagittis elit tempus vitae. Sed nec luctus tellus. Nunc facilisis elementum risus, faucibus venenatis lorem iaculis vel. Cras a purus id odio semper aliquet. Aenean sit amet lorem quis sapien vulputate porttitor. Aliquam placerat lacus lacus, sit amet viverra odio facilisis eu. Cras tincidunt diam fermentum felis accumsan, at scelerisque arcu pulvinar. Nunc finibus vulputate pulvinar. In id urna at mauris imperdiet porta id ac metus. Vivamus quis lacus sed orci facilisis tempor. Proin eu justo urna.
			</p>

		</div>

		<div class='clear'>&nbsp;</div>
	</div>
	
</section>