---
Name: core
After: 'framework/*','cms/*'
---
OP\studentsuccess\DateUtils:
  PublicDateTimeFormat: 'd F Y H:i'
  PublicDateFormat: 'd F Y'
  PublicTimeFormat: 'H:i a'
SilverStripe\Forms\DateField:
  default_config:
    showcalendar: true
    dateformat: dd/MM/yyyy
SilverStripe\Assets\Image:
  extensions:
    - OP\studentsuccess\ImageExtension
OP\studentsuccess\ImageExtension:
  sizes: null
  exclude_classes: null
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - OP\studentsuccess\CoreConfigs
SilverStripe\Control\Controller:
  extensions:
    - OP\studentsuccess\SS_MinifiedResponseExtension

SilverStripe\Control\Director:
  rules:
    search: OP\studentsuccess\SearchPage
