---
Name: core

---
OP\Studentsuccess\DateUtils:
  PublicDateTimeFormat: 'd F Y H:i'
  PublicDateFormat: 'd F Y'
  PublicTimeFormat: 'H:i a'
SilverStripe\Forms\DateField:
  default_config:
    showcalendar: true
    dateformat: dd/MM/yyyy
SilverStripe\Assets\Image:
  extensions:
    - OP\Studentsuccess\ImageExtension
OP\Studentsuccess\ImageExtension:
  sizes: null
  exclude_classes: null
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - OP\Studentsuccess\CoreConfigs
SilverStripe\Control\Controller:
  extensions:
    - OP\Studentsuccess\SS_MinifiedResponseExtension

SilverStripe\Control\Director:
  rules:
    search: OP\Studentsuccess\SearchPage
